### ISSUE TITLE
Test generated manifests against rustup

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust-central-station#17] opened 2017-06-22 17:02 UTC
Refiling https://github.com/rust-lang/rust/issues/41767 here.

Several times, PRs have changed the format of the manifests in such a way that they can no longer be installed by rustup. This results in the corresponding nightlies being uninstallable, and doesn't give much time to fix it before the next nightly: https://github.com/rust-lang-nursery/rustup.rs/issues/1092#issuecomment-299374487

We should add tests to catch these problems before they occur.

**Comment by pietroalbini** [comment] 2020-10-26 10:20
Duplicate of https://github.com/rust-lang/promote-release/issues/15.

**Closed by pietroalbini** 2020-10-26 10:20 UTC
Labels: A-nightlies
